channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.10.12

  - pip=23.2.1
  - pip:
      # Define pip packages here.
      # https://pypi.org/
      - rpaframework==27.1.0 # https://rpaframework.org/releasenotes.html
      - rpaframework-recognition==5.2.0
      - pandas==2.0.2
      # - pyodbc==4.0.39
      # - abydos==0.5.0
      # - python-Levenshtein==0.21.1
      # - xmltodict==0.13.0
      - nepali_datetime==1.0.7
      - pymysql==1.1.0
      - XlsxWriter==3.2.0
      - oracledb==2.2.0
      